const { readFileSync } = require("fs")
const orig = readFileSync(0).toString('base64')
const sc = btoa(readFileSync("inner-script.tpl.js").replace("/* code */", JSON.stringify(orig)))
const sc2 = readFileSync("outer-script.tpl.js").replace("/* code */", JSON.stringify(sc)))
process.stdout.write(sc2)
